spring:
  application:
    name:  consumer
  kafka:
    bootstrap-servers:  localhost:29092
    consumer:
      auto-offset-reset:  earliest
      group-id:  message_group_id
  #spring.kafka.bootstrap-servers=localhost:29092
#      properties:
#        spring:
#          json:
#            trusted:
#            packages:  *
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer:  org.apache.kafka.common.serialization.StringDeserializer
